### ISSUE TITLE
add a non-snapshot Collection.Get(key, ReaderOptions) API

### ISSUE THREAD

**Issue by steveyen** [couchbase/moss#15]
If a user just wants to lookup a single item in a collection, they have to first create a snapshot, then snapshot.Get(), then snapshot.Close().

One issue is creating a snapshot means memory allocations (of the snapshot instance and taking a copy of the segment stack).

A "onesie" API to just lookup a single item, if it can be implemented efficiently (without undue memory allocations and with having to hold a lock for a long time), more be more convenient for folks to grok.

(See also https://github.com/couchbase/moss/issues/14)

**Comment by abhinavdangeti** [comment]
http://review.couchbase.org/#/c/75288/

**Comment by steveyen** [comment]
Thanks @abhinavdangeti for adding the Collection.Get() API
