### ISSUE TITLE
optimization idea: copy-on-write, ref-counted segmentStack's

### ISSUE THREAD

**Issue by steveyen** [couchbase/moss#28]
Currently, creating snapshot copies the the segment stack, which means memory allocations and copying of pointers.  Instead, perhaps creating a snapshot should just bump a ref-count on some existing segmentStack which should be treated as immutable (except for the ref-count).

Whenever a writer (such as ExecuteBatch, the background Merger, etc) wants to modify the segmentStack, it should use copy-on-write.

The existing moss implementation actually does parts of the above anyways, so we might be near to that already.

**Comment by hisundar** [comment]
I suppose this is an optimization for the quiescent period where snapshots are taken in the absence of new writes, right?
If so how about this implementation idea - every collection just has a 
latestSnapshot *Snapshot
On every collection level Snapshot(), this variable is examined. 
If it is nil, a new snapshot is taken and this variable is set to it and returned.
If it is not nil, its reference count is bumped up, thereby re-using the snapshot.
When ExecuteBatch(), collection_merger or persisters get their locks, they simply set this variable to nil, thereby invalidating the latestSnapshot.

**Comment by steveyen** [comment]
Simple approach -- I like it!

**Comment by hisundar** [comment]
Implementation uploaded here http://review.couchbase.org/77284. thanks

**Comment by steveyen** [comment]
thanks @hisundar for nailing this one
