### ISSUE TITLE
Buckets?

### ISSUE THREAD

**Issue by ivanjaros** [couchbase/moss#55]
Hi, from the description it is not obvious to me if moss supports buckets(like bolt)?

There is the
> child collections allow multiple related collections to be atomically grouped

which I'm not exactly sure if it is something like buckets or it is just a bunch of selected records manually put together?

**Comment by mschoch** [comment]
I think it is functionally similar, in that the application can group together a bunch of items under a name, and have a separate key-space to work with.  And typically this performs better than prefixing all the keys with some identifier.

That said, I'm sure the implementations are much different, so questions like, "Can I create millions of buckets/child-collections?" may have different answers.

**Comment by ivanjaros** [comment]
Yes, I just want to be able to basically have multiple values per key's value. That's buckets in BoltDB really, no magic.
