### ISSUE TITLE
Are calls atomic?

### ISSUE THREAD

**Issue by vikramdurai** [couchbase/moss#58]
Are `set` and `get` calls atomic?

**Comment by mschoch** [comment]
In moss a `Batch` is the unit of atomicity.  If you need a `set` operation to be atomic, you can put it in it's own batch.

Get operations do not mutate the system, so the notion of atomicity doesn't really apply.  Instead there is a notion of isolated read snapshots.  You can get stable reads of a point in time by sharing common snapshot.

**Comment by vikramdurai** [comment]
so `get` calls don't block?
