### ISSUE TITLE
Iterator only returning one record

### ISSUE THREAD

**Issue by tleyden** [couchbase/moss#6]
I'm using [this code](https://gist.github.com/tleyden/0919c01e154d039d77cffe8c2b957393) to store and retrieve records from moss.

But when I call `GetStoredSQSMessages()` it only seems to return the _last_ entry, as opposed to all the entries.

If I run `strings data-0000000000000001.moss` I can see all the records I'm expecting, so I know their somewhere in the moss, but I just can't get at them w/ the iterator.

Can you take a look at my [GetStoredSQSMessages](https://gist.github.com/tleyden/0919c01e154d039d77cffe8c2b957393#file-gistfile1-txt-L70) method and see if I'm doing anything wrong.

If nothing is obvious, should I try repro'ing this in a unit test?  I'm storing the moss in a docker volume mount, so it's possible I'm doing something funny (but like I said I can see all the records with `strings`, so it seems to be an iterator problem)

**Comment by steveyen** [comment]
Maybe the comparison on line 107 ha the bit flipped?  https://gist.github.com/tleyden/0919c01e154d039d77cffe8c2b957393#file-gistfile1-txt-L107

That is, on success, the err will be nil so the loop will end too early?

**Comment by tleyden** [comment]
Oops!  Thanks for catching that.
