### ISSUE TITLE
support for multiple collections

### ISSUE THREAD

**Issue by steveyen** [couchbase/moss#7]
Users can currently fake out multiple collections by explicitly adding a short collection name prefix to each of their keys.  However, such a trick is suboptimal as it repeats a prefix for every key-val item.

Instead, a proposal to support multiple collections natively in moss would be by introducing a few additional methods to the API, so that we remain backwards compatible for current moss users.

The idea is that the current Collection in moss now logically becomes a "top-most" collection of an optional hierarchy of child collections.

To the Batch interface, the proposal is to add the methods...

    NewChildCollectionBatch(childCollectionName string, hints) (Batch, error)

    DelChildCollection(childCollectionName string) error

When a batch is executed, the entire hierarchy of a top-level batch and its batches for any child collections will be committed atomically.

Removing a child collection takes precedence over adding more child collection mutations.

To the Snapshot interface, the proposal is to add the methods...

    ChildCollectionNames() ([]string, error)

    ChildCollectionSnapshot(childCollectionName string) (Snapshot, error)

And, that's it.

The proposed API allows for deeply nested child collections of child collections, but the initial implementation might just return an error if the user tries to have deep nesting.

**Comment by hisundar** [comment]
Implementation as per design above up for review here
http://review.couchbase.org/#/c/72254

**Comment by steveyen** [comment]
@hisundar improvement for this went in -- thanks Sundar!
